package me.xbackpack.galaxysky.enum.customItems

import me.xbackpack.galaxysky.api.item.Item
import me.xbackpack.galaxysky.registry.item.Items
import me.xbackpack.galaxysky.registry.item.Materials
import me.xbackpack.galaxysky.registry.item.Pickaxes

enum class GalaxySkyItem(
    val item: Item,
) {
    // Items
    AFK_TOKEN(Items.AFK_TOKEN),

    // Materials
    COBBLESTONE(Materials.COBBLESTONE),
    COAL(Materials.COAL),
    COPPER(Materials.COPPER),
    IRON(Materials.IRON),
    GOLD(Materials.GOLD),
    DIAMOND(Materials.DIAMOND),
    QUARTZ(Materials.QUARTZ),
    OBSIDIAN(Materials.OBSIDIAN),
    NETHERITE_SCRAP(Materials.NETHERITE_SCRAP),
    REDSTONE(Materials.REDSTONE),
    MAGMA(Materials.MAGMA),
    NETHERITE(Materials.NETHERITE),
    RUBY(Materials.RUBY),
    SAPPHIRE(Materials.SAPPHIRE),
    PURPUR(Materials.PURPUR),
    LAPIS(Materials.LAPIS),
    CHARGED_STONE(Materials.CHARGED_STONE),
    PRISMARINE(Materials.PRISMARINE),
    OPAL(Materials.OPAL),
    STRENGTHENED_COBBLESTONE(Materials.STRENGTHENED_COBBLESTONE),
    STRENGTHENED_COAL(Materials.STRENGTHENED_COAL),
    STRENGTHENED_COPPER(Materials.STRENGTHENED_COPPER),
    STRENGTHENED_IRON(Materials.STRENGTHENED_IRON),
    STRENGTHENED_GOLD(Materials.STRENGTHENED_GOLD),
    STRENGTHENED_DIAMOND(Materials.STRENGTHENED_DIAMOND),
    STRENGTHENED_QUARTZ(Materials.STRENGTHENED_QUARTZ),
    STRENGTHENED_OBSIDIAN(Materials.STRENGTHENED_OBSIDIAN),
    STRENGTHENED_NETHERITE_SCRAP(Materials.STRENGTHENED_NETHERITE_SCRAP),
    STRENGTHENED_REDSTONE(Materials.STRENGTHENED_REDSTONE),
    STRENGTHENED_MAGMA(Materials.STRENGTHENED_MAGMA),
    STRENGTHENED_NETHERITE(Materials.STRENGTHENED_NETHERITE),
    STRENGTHENED_RUBY(Materials.STRENGTHENED_RUBY),
    STRENGTHENED_SAPPHIRE(Materials.STRENGTHENED_SAPPHIRE),
    STRENGTHENED_PURPUR(Materials.STRENGTHENED_PURPUR),
    STRENGTHENED_LAPIS(Materials.STRENGTHENED_LAPIS),
    STRENGTHENED_CHARGED_STONE(Materials.STRENGTHENED_CHARGED_STONE),
    STRENGTHENED_PRISMARINE(Materials.STRENGTHENED_PRISMARINE),
    STRENGTHENED_OPAL(Materials.STRENGTHENED_OPAL),
    COMPACT_COBBLESTONE(Materials.COMPACT_COBBLESTONE),
    COMPACT_COAL(Materials.COMPACT_COAL),
    COMPACT_COPPER(Materials.COMPACT_COPPER),
    COMPACT_IRON(Materials.COMPACT_IRON),
    COMPACT_GOLD(Materials.COMPACT_GOLD),
    COMPACT_DIAMOND(Materials.COMPACT_DIAMOND),
    COMPACT_QUARTZ(Materials.COMPACT_QUARTZ),
    COMPACT_OBSIDIAN(Materials.COMPACT_OBSIDIAN),
    COMPACT_NETHERITE_SCRAP(Materials.COMPACT_NETHERITE_SCRAP),
    COMPACT_REDSTONE(Materials.COMPACT_REDSTONE),
    COMPACT_MAGMA(Materials.COMPACT_MAGMA),
    COMPACT_NETHERITE(Materials.COMPACT_NETHERITE),
    COMPACT_PURPUR(Materials.COMPACT_PURPUR),
    COMPACT_LAPIS(Materials.COMPACT_LAPIS),
    COMPACT_CHARGED_STONE(Materials.COMPACT_CHARGED_STONE),
    COMPACT_PRISMARINE(Materials.COMPACT_PRISMARINE),
    COMPACT_OPAL(Materials.COMPACT_OPAL),

    // Pickaxes
    WOODEN_PICKAXE_1(Pickaxes.WOODEN_PICKAXE_1),
    ADMIN_PICKAXE(Pickaxes.ADMIN_PICKAXE),
}
